SIH-POSHAN/SIH_Meraki/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# import settings and static first
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.indexview, name='home'),
    path('admin/login/', LoginView.as_view(template_name='accounts/login.html',
                                           redirect_authenticated_user=True),
         ),
    path('admin/', admin.site.urls),
    path('placeholder', views.PlaceholderView.as_view(),                name='placeholder'),
    path('accounts/', include('accounts.urls',                          namespace='accounts')),
    path('states/', include('states.urls',                              namespace='states')),
    path('districts/', include('districts.urls',                        namespace='districts')),
    path('schools/', include('schools.urls',                            namespace='schools')),
    path('talukas/', include('talukas.urls',                            namespace='talukas')),

]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SIH-POSHAN/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeDoneView,
    PasswordChangeView
)
from .views import password_reset_request


app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='accounts/login.html',
                           redirect_authenticated_user=True),
         name='login'),

    path('logout/',
         LogoutView.as_view(),
         name='logout'),

    path('change_password/',
         PasswordChangeView.as_view(
             template_name='accounts/password_change_form.html',
             success_url=reverse_lazy('accounts:password_change_done')
         ),
         name='password_change'),

    path('password_change_done/',
         PasswordChangeDoneView.as_view(
             template_name='accounts/password_change_done.html'
         ),
         name='password_change_done'),

    # path('password_reset',
    #      PasswordResetView.as_view(
    #          template_name='accounts/password_reset.html',
    #          email_template_name='accounts/password_reset_email.html',
    #          subject_template_name='accounts/password_reset_subject.txt',
    #          success_url=reverse_lazy('accounts:password_reset_done')
    #      ),
    #      name='password_reset'),
    
    path('password_reset', password_reset_request, name='password_reset'),

    path('password_reset_done/',
         PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_<uidb64>_<token>/',
         PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts:password_reset_complete')
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

SIH-POSHAN/districts/urls.py
from django.urls import path, include, reverse_lazy
from . import views

app_name = 'districts'

urlpatterns = [
    # DISTRICT
    path(
        route= '',                    
        view = views.dashboardView,                
        name = 'dashboard'
    ),
    
    # SCHOOL
    path(
        route= 'register_school/',                    
        view = views.SchoolCreateView.as_view(),                
        name = 'register_school'
    ),
    path(
        route= 'manage_schools/',                    
        view = views.SchoolList.as_view(),                
        name = 'manage_schools'
    ),
    path(
        route= 'school_detail/<pk>/',                    
        view = views.SchoolDetail.as_view(),                
        name = 'school_detail'
    ),
]

SIH-POSHAN/schools/urls.py
from django.urls import path, include, reverse_lazy
from . import views


app_name = 'schools'

urlpatterns = [
    # SCHOOL
    path('dashboard/',                    views.dashboardView,                name='dashboard'),
    path('profile/',            views.profileView,                  name='profile'),
    path('update_profile_pic/', views.update_profile_pic,           name='update_profile_pic'),
    
    # MEAL
    path('meal/',views.Meal_add.as_view(),     name='todays_meal'),
    path('meal_detail/<pk>/',   views.MealDetailView.as_view(),     name='meal_detail'),
    
    # STUDENT
    path('register_students/',views.register_stu.as_view(),name='register'),
    path('create_students/',    views.StudentCreateView.as_view(),  name='create_students'),
    path('attendence/',         views.attendance.as_view(),               name='attendence'),
    path('student_details/<pk>/',  views.profile_get.as_view(), name='student_detail'),
    # path('regiter_students/')

    
    # CLASS
    path('create_class/',       views.ClassCreateView.as_view(),    name='create_class'),
    path('class_detail/<pk>/',  views.ClassDetailView.as_view(),    name='class_detail'),
    path('manage_class/',       views.ClassListView.as_view(),      name='manage_class'),
    path('update_class/<pk>/',  views.ClassUpdateView.as_view(),    name='update_class'),
    path('delete_class/<pk>/',  views.ClassDeleteView,              name='delete_class'),
    
]

SIH-POSHAN/states/urls.py
from django.urls import path, include, reverse_lazy
from .views import StateCreateView

app_name = 'states'

urlpatterns = [
    path('create_new/', StateCreateView.as_view(), name='create'), 
    
    ]


    

SIH-POSHAN/districts/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from states.models import State
import os
from django.contrib.auth.models import Group
from merakiiextras.common import get_current_datetime
from slugify import slugify



# Create your models here.

def _(something):
    return something

def rename_upload_image_district_profile(instance, filename):
    ext = filename.split('.')[-1]
    filename = "profile/district/%s/%s/%s.%s.%s" % (instance.user, instance.name, filename, get_current_datetime(), ext)
    return (os.path.join('images/', filename))

class District(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='districts')
    name = models.CharField(max_length=150)
    email = models.EmailField( max_length=254)
    profile_pic= models.ImageField(blank=False, upload_to=rename_upload_image_district_profile)
    address_line1 = models.CharField( max_length=250)
    address_line2 = models.CharField( max_length=250)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
                                )
    contact_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='districts')
    

    class Meta:
        verbose_name = _("district")
        verbose_name_plural = _("districts")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("district_detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        u = self.user
        u.email = self.email
        u.save()
        my_group = Group.objects.get(name='districts') 
        my_group.user_set.add(self.user)
        print(self.user)
        return super(District, self).save(*args, **kwargs)

SIH-POSHAN/schools/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from talukas.models import Taluka
from districts.models import District
import os
import re
from django.contrib.auth.models import Group
from merakiiextras.common import get_current_datetime

def _(something):
    return something

def year_choices():
    choices = [(r,r) for r in reversed(range(1990, timezone.now().year+2))]
    # choices = choices.reverse()
    return choices

def current_year():
    return timezone.now().year+1

def std_choices():
    choices = [(-2, 'Jr. KG'),(-1, 'Sr. KG')]
    choices.extend([(r,r) for r in range(1,9)])
    return choices

def rename_upload_image_school_profile(instance, filename):
    ext = filename.split('.')[-1]
    filename = "profile/school/%s/%s/%s.%s.%s.%s" % (instance.user, instance.name, instance.udise_code, filename, get_current_datetime(), ext)
    return (os.path.join('images/', filename))

class School(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='schools')
    email = models.EmailField( max_length=254)
    name = models.CharField(max_length=150)
    udise_code = models.CharField(max_length=150, unique=True)
    profile_pic= models.ImageField(blank=False, upload_to=rename_upload_image_school_profile)
    # ADDRESS
    address_line1 = models.CharField( max_length=250)
    address_line2 = models.CharField( max_length=250)
    pincode = models.PositiveIntegerField()
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='schools')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
                                )
    contact_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    
    
    class Meta:
        verbose_name = "school"
        verbose_name_plural = "schools"

    def __str__(self):
        return f"{self.name} - ({self.district})"

    def get_absolute_url(self):
        return reverse("school_detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        
        u = self.user
        u.email = self.email
        u.save()
        my_group = Group.objects.get(name='schools') 
        my_group.user_set.add(self.user)
        print(self.user)
        return super(School, self).save(*args, **kwargs)

class Class(models.Model):
    class_std = models.IntegerField(choices=std_choices())
    class_name = models.CharField(max_length=50, unique=True)
    year = models.IntegerField(choices=year_choices(), default=current_year)
    school = models.ForeignKey(School, on_delete=models.CASCADE,related_name='classes')

    class Meta:
        verbose_name = "class"
        verbose_name_plural = "clases"
        unique_together = ('class_name', 'year', 'school')

    def __str__(self):
        return f"{self.class_name} - ({self.school})"

    def get_absolute_url(self):
        return reverse("schools:class_detail", kwargs={"pk": self.pk})

class Student(models.Model):

    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    mother_name = models.CharField(max_length=150, blank=True, null=True)
    father_name = models.CharField(max_length=150, blank=True, null=True)
    dob = models.DateField()
    current_class = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='students')
    gr_no = models.CharField(max_length=50)
    roll_no = models.CharField(max_length=50)
    current_height = models.FloatField(blank=True, null=True)
    current_weight = models.FloatField(blank=True, null=True)
    # age = models.IntegerField(blank=True, null=True)
    created  = models.DateTimeField(editable=False, default=timezone.now)
    modified = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = "student"
        verbose_name_plural = "students"
        unique_together = ('current_class', 'gr_no',)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.gr_no}) ({self.current_class})"

    def get_absolute_url(self):
        return reverse("schools:student_detail", kwargs={"pk": self.pk})

    # def get_queryset(self, *args, **kwargs):
    #     qs = super(Student, self).get_queryset().annotate(age=int(self.calculate_age(self)))
    #     return qs
    
    @property    
    def age(self):
        born = self.dob
        today = timezone.now()
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
        
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Student, self).save(*args, **kwargs)
    
    @property    
    def calculate_age(self):
        born = self.dob
        today = timezone.now()
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

def rename_upload_image_meals(instance, filename):
    ext = filename.split('.')[-1]
    filename = "meals/%s/%s/%s.%s.%s.%s.%s" % (instance.school, instance.date, instance.name, str(instance.date), filename, get_current_datetime(), ext)
    return os.path.join('images/', filename)



class Meal(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='meals')
    name = models.CharField("Meal Name",max_length=999)
    date = models.DateField(default=timezone.now, blank=False, null=False)
    meal_pic= models.ImageField(blank=False, upload_to = rename_upload_image_meals)
    calories = models.FloatField(blank=True, null=True)
    proteins = models.FloatField(blank=True, null=True)

    class Meta:
        verbose_name = _("meal")
        verbose_name_plural = _("meals")
        unique_together = ('school','date')

    def __str__(self):
        return f"{self.name} ({self.date}) ({self.school.name})"

    def get_absolute_url(self):
        return reverse("schools:meal_detail", kwargs={"pk": self.pk})


class Attendence(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("attendence")
        verbose_name_plural = _("attendences")
        unique_together = ('meal', 'student')

    def __str__(self):
        return f"{self.student} ----> {self.meal.date}"

    def get_absolute_url(self):
        return reverse("attendence_detail", kwargs={"pk": self.pk})

SIH-POSHAN/districts/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required, user_passes_test
from .permissions import is_in_group_districts
from django.utils import timezone
from django.contrib import messages
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, DetailView, UpdateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from schools.models import School
from .forms import SchoolForm
from .models import District

# Create your views here.
# Create your views here.
@user_passes_test(is_in_group_districts, login_url='/')
@login_required
def dashboardView(request):
    return render(request, 'districts/dashboard.html')

class SchoolCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = School
    template_name = "districts/register_school.html"
    form_class = SchoolForm
    
    def form_valid(self, form):
        form.instance.district = self.request.user.districts
        return super().form_valid(form)
    
    def test_func(self):
        cond1 = is_in_group_districts(self.request.user)
        return cond1
    
class SchoolDetail(DetailView):
    model = School
    context_object_name= 'school'
    template_name='districts/school_detail.html'



class SchoolList(ListView):
    model = School
    template_name='districts/manage_schools.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['school_list'] = self.request.user.districts.schools.all()
        return context

class DistrictDetail(DetailView):
    model = District
    template_name='districts/manage_schools.html'
    context_object_name= 'district'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['school_list'] = self.request.user.schools.all()
        return context

SIH-POSHAN/districts/templates/districts/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Title -->
  <title>
    {% block title %}
    Dashboard
    {% endblock title %}
  </title>

  <!-- Head -->
  {% block head %}

  {% endblock head %}

  <!-- Style -->
  {% block style %}
  <style> </style>
  {% endblock style %}
</head>

<body>

  <nav class="nav justify-content-center">
    <a class="nav-link active" href="{% url 'districts:dashboard' %}">Home</a>
    <a class="nav-link" href="{% url 'districts:register_school' %}">Register School</a>
    <a class="nav-link" href="{% url 'districts:manage_schools' %}">Manage School</a>
    <a class="nav-link " href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-danger">Logout</button></a>
  </nav>


  <!-- Body -->
  {% block body %}
  This is Base FILE.



  {% endblock body %}


  <!-- Script -->
  {% block script %}
  <script>    </script>
  {% endblock script %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

SIH-POSHAN/districts/templates/districts/dashboard.html
{% extends "districts/base.html" %}

<!-- load static -->
{% load static %}

<!-- Title BLOCK -->
{% block title %}
Dashboard
{% endblock title %}

<!-- HEAD BLOCK -->
{% block head %}

{% endblock head %}

<!-- STYLE BLOCK -->
{% block style %}

{% endblock style %}


<!-- Body BLOCK -->
{% block body %}

<div class="container">
    <h1>This is District dashboard</h1>
</div>


{% endblock body %}

<!-- Script BLOCK -->

{% block script %}
<script>





</script>

{% endblock script %}

SIH-POSHAN/districts/templates/districts/manage_schools.html
{% extends "districts/base.html" %}

<!-- ----------------------------------------------load static---------------------------------------------- -->
{% load static %}

<!-- ----------------------------------------------Title BLOCK---------------------------------------------- -->
{% block title %}
Manage Schools
{% endblock title %}

<!-- ----------------------------------------------HEAD BLOCK---------------------------------------------- -->
{% block head %}

{% endblock head %}

<!-- ----------------------------------------------STYLE BLOCK---------------------------------------------- -->
{% block style %}

<style>


</style>

{% endblock style %}


<!-- ----------------------------------------------Body BLOCK---------------------------------------------- -->
{% block body %}

<div class="container">

    <div class="card-deck">

        {% for school in school_list %}
        <p>
        <div class="card shadow-lg">
            <div class="card-body">
                <h5 class="card-title">{{school.class_name}}</h5>
                <p class="card-text">
                    {{class.class_std}}
                    {{class.school}}
                    {{class.year}}
                <ul>
                    {% for student in class.students.all %}
                    <li>
                        {{student}}
                        <br>
                    </li>
                    {% endfor %}
                </ul>
                </p>
                <a href="{% url 'schools:class_detail' pk=class.id %}" class="btn btn-primary">Details</a>
                <a onclick="confirm_delete_class('{{class.id}}');" class="btn btn-danger" role="button">Delete</a>

            </div>


        </div>
        </p>

        {% endfor %}
    </div>


</div>

{% endblock body %}

<!-- ----------------------------------------------Script BLOCK---------------------------------------------- -->

{% block script %}
<script>





</script>

{% endblock script %}

SIH-POSHAN/districts/templates/districts/register_school.html
{% extends "districts/base.html" %}

<!-- load static -->
{% load static %}

<!-- Title BLOCK -->
{% block title %}
Register School
{% endblock title %}

<!-- HEAD BLOCK -->
{% block head %}

{% endblock head %}

<!-- STYLE BLOCK -->
{% block style %}

{% endblock style %}


<!-- Body BLOCK -->
{% block body %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>



{% endblock body %}

<!-- Script BLOCK -->

{% block script %}
<script>





</script>

{% endblock script %}

SIH-POSHAN/districts/templates/districts/sample_template.html
{% extends "districts/base.html" %}

<!-- ----------------------------------------------load static---------------------------------------------- -->
{% load static %}

<!-- ----------------------------------------------Title BLOCK---------------------------------------------- -->
{% block title %}
Dashboard
{% endblock title %}

<!-- ----------------------------------------------HEAD BLOCK---------------------------------------------- -->
{% block head %}

{% endblock head %}

<!-- ----------------------------------------------STYLE BLOCK---------------------------------------------- -->
{% block style %}

<style>


</style>

{% endblock style %}


<!-- ----------------------------------------------Body BLOCK---------------------------------------------- -->
{% block body %}



{% endblock body %}

<!-- ----------------------------------------------Script BLOCK---------------------------------------------- -->

{% block script %}
<script>





</script>

{% endblock script %}

SIH-POSHAN/districts/templates/districts/school_detail.html
{% extends "districts/base.html" %}

<!-- ----------------------------------------------load static---------------------------------------------- -->
{% load static %}

<!-- ----------------------------------------------Title BLOCK---------------------------------------------- -->
{% block title %}
School Details
{% endblock title %}

<!-- ----------------------------------------------HEAD BLOCK---------------------------------------------- -->
{% block head %}

{% endblock head %}

<!-- ----------------------------------------------STYLE BLOCK---------------------------------------------- -->
{% block style %}

<style>


</style>

{% endblock style %}


<!-- ----------------------------------------------Body BLOCK---------------------------------------------- -->
{% block body %}

<div class="container">
    {{school}}
</div>

{% endblock body %}

<!-- ----------------------------------------------Script BLOCK---------------------------------------------- -->

{% block script %}
<script>





</script>

{% endblock script %}