SIH-POSHAN/SIH_Meraki/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# import settings and static first
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.indexview, name='home'),
    path('admin/login/', LoginView.as_view(template_name='accounts/login.html',
                                           redirect_authenticated_user=True),
         ),
    path('admin/', admin.site.urls),
    path('placeholder', views.PlaceholderView.as_view(),                name='placeholder'),
    path('accounts/', include('accounts.urls',                          namespace='accounts')),
    path('states/', include('states.urls',                              namespace='states')),
    path('districts/', include('districts.urls',                        namespace='districts')),
    path('schools/', include('schools.urls',                            namespace='schools')),
    path('talukas/', include('talukas.urls',                            namespace='talukas')),

]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SIH-POSHAN/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeDoneView,
    PasswordChangeView
)
from .views import password_reset_request


app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='accounts/login.html',
                           redirect_authenticated_user=True),
         name='login'),

    path('logout/',
         LogoutView.as_view(),
         name='logout'),

    path('change_password/',
         PasswordChangeView.as_view(
             template_name='accounts/password_change_form.html',
             success_url=reverse_lazy('accounts:password_change_done')
         ),
         name='password_change'),

    path('password_change_done/',
         PasswordChangeDoneView.as_view(
             template_name='accounts/password_change_done.html'
         ),
         name='password_change_done'),

    # path('password_reset',
    #      PasswordResetView.as_view(
    #          template_name='accounts/password_reset.html',
    #          email_template_name='accounts/password_reset_email.html',
    #          subject_template_name='accounts/password_reset_subject.txt',
    #          success_url=reverse_lazy('accounts:password_reset_done')
    #      ),
    #      name='password_reset'),
    
    path('password_reset', password_reset_request, name='password_reset'),

    path('password_reset_done/',
         PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_<uidb64>_<token>/',
         PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts:password_reset_complete')
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

SIH-POSHAN/states/urls.py
from django.urls import path, include, reverse_lazy
from .views import StateCreateView

app_name = 'states'

urlpatterns = [
    path('create_new/', StateCreateView.as_view(), name='create'), 
    
    ]


    

SIH-POSHAN/talukas/urls.py
from django.urls import path, include, reverse_lazy
from . import views

app_name = 'talukas'

urlpatterns = [
    path('dashboard/', views.dashboardView, name='dashboard'),
    path('profile/', views.profileView, name='profile'),
    path('register_schools/', views.registerSchoolsView, name='register_schools'),
    

]

SIH-POSHAN/talukas/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from districts.models import District 
import os



# Create your models here.

def _(something):
    return something

def rename_upload_image_taluka_profile(instance, filename):
    ext = filename.split('.')[-1]
    filename = "profile/taluka/%s/%s/%s.%s" % (instance.user, instance.name,  filename, ext)
    return os.path.join('images/', filename)

class Taluka(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='talukas')
    name = models.CharField(max_length=150)
    profile_pic= models.ImageField(blank=False, upload_to=rename_upload_image_taluka_profile)
    address_line1 = models.CharField( max_length=250)
    address_line2 = models.CharField( max_length=250)
    pincode = models.PositiveIntegerField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
                                )
    contact_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Taluka")
        verbose_name_plural = _("Talukas")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Taluka_detail", kwargs={"pk": self.pk})

SIH-POSHAN/talukas/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from .permissions import is_in_group_talukas


# Create your views here.
@user_passes_test(is_in_group_talukas) 
def dashboardView(request):
    return  render(request, 'talukas/index.html')

@user_passes_test(is_in_group_talukas) 
def profileView(request):
    return  render(request, 'talukas/profile.html')

# @user_passes_test(is_in_group_talukas) 
def registerSchoolsView(request):
    return  render(request, 'talukas/register-school.html')

SIH-POSHAN/talukas/templates/talukas/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
    />
    <title>{% block title %}Home{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'talukas/bootstrap/css/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.12.0/css/all.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'talukas/fonts/fontawesome5-overrides.min.css' %}" />
  </head>

  <body id="page-top">
    <div id="wrapper">
      <nav
        class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0"
      >
        <div class="container-fluid d-flex flex-column p-0">
          <a
            class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0"
            href="#"
          >
            <div class="sidebar-brand-icon">
              <i class="fas fa-warehouse"></i>
            </div>
            <div class="sidebar-brand-text mx-3"><span>TALUKA</span></div>
          </a>
          <hr class="sidebar-divider my-0" />
          <ul class="navbar-nav text-light" id="accordionSidebar">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'talukas:dashboard' %}"
                ><i class="fas fa-tachometer-alt"></i><span>Dashboard</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'talukas:profile' %}"
                ><i class="fas fa-user"></i><span>Profile</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'talukas:register_schools' %}"
                ><i class="fas fa-table"></i><span>Register Schools</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="#"
                ><i class="fa fa-file-pdf-o"></i
                ><span>Generate Reports</span></a
              >
            </li>
          </ul>
          <div class="text-center d-none d-md-inline">
            <button
              class="btn rounded-circle border-0"
              id="sidebarToggle"
              type="button"
            ></button>
          </div>
        </div>
      </nav>
      <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
          <nav
            class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top"
          >
            <div class="container-fluid">
              <button
                class="btn btn-link d-md-none rounded-circle me-3"
                id="sidebarToggleTop"
                type="button"
              >
                <i class="fas fa-bars"></i>
              </button>
              <ul class="navbar-nav flex-nowrap ms-auto">
                <li class="nav-item dropdown d-sm-none no-arrow">
                  <a
                    class="dropdown-toggle nav-link"
                    aria-expanded="false"
                    data-bs-toggle="dropdown"
                    href="#"
                    ><i class="fas fa-search"></i
                  ></a>
                  <div
                    class="dropdown-menu dropdown-menu-end p-3 animated--grow-in"
                    aria-labelledby="searchDropdown"
                  >
                    <form class="me-auto navbar-search w-100">
                      <div class="input-group">
                        <input
                          class="bg-light form-control border-0 small"
                          type="text"
                          placeholder="Search for ..."
                        />
                        <div class="input-group-append">
                          <button class="btn btn-primary py-0" type="button">
                            <i class="fas fa-search"></i>
                          </button>
                        </div>
                      </div>
                    </form>
                  </div>
                </li>
                <li class="nav-item dropdown no-arrow mx-1">
                  <div class="nav-item dropdown no-arrow">
                    <a
                      class="dropdown-toggle nav-link"
                      aria-expanded="false"
                      data-bs-toggle="dropdown"
                      href="#"
                      ><span class="badge bg-danger badge-counter">1+</span
                      ><i class="fas fa-bell fa-fw"></i
                    ></a>
                    <div
                      class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in"
                    >
                      <h6 class="dropdown-header">alerts center</h6>
                      <a
                        class="dropdown-item d-flex align-items-center"
                        href="#"
                      >
                        <div class="me-3">
                          <div class="bg-primary icon-circle">
                            <i class="fas fa-file-alt text-white"></i>
                          </div>
                        </div>
                        <div>
                          <span class="small text-gray-500"
                            >December 12, 2019</span
                          >
                          <p>A new monthly report is ready to download!</p>
                        </div> </a
                      ><a
                        class="dropdown-item text-center small text-gray-500"
                        href="#"
                        >Show All Alerts</a
                      >
                    </div>
                  </div>
                </li>
                <div class="d-none d-sm-block topbar-divider"></div>
                <li class="nav-item dropdown no-arrow">
                  <div class="nav-item dropdown no-arrow">
                    <a
                      class="dropdown-toggle nav-link"
                      aria-expanded="false"
                      data-bs-toggle="dropdown"
                      href="#"
                      ><span class="d-none d-lg-inline me-2 text-gray-600 small"
                        >Thane</span
                      ></a
                    >
                    <div
                      class="dropdown-menu shadow dropdown-menu-end animated--grow-in"
                    >
                      <a class="dropdown-item" href="#"
                        ><i
                          class="fas fa-user fa-sm fa-fw me-2 text-gray-400"
                        ></i
                        >&nbsp;Profile</a
                      ><a class="dropdown-item" href="#"
                        ><i
                          class="fas fa-list fa-sm fa-fw me-2 text-gray-400"
                        ></i
                        >&nbsp;Activity log</a
                      >
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'accounts:logout' %}"
                        ><i
                          class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"
                        ></i
                        >&nbsp;Logout</a
                      >
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </nav>

          {% block content %}{% endblock content %}
        </div>
        <footer class="bg-white sticky-footer">
          <div class="container my-auto">
            <div class="text-center my-auto copyright">
              <span>Copyright © Meraki 2022</span>
            </div>
          </div>
        </footer>
      </div>
      <a class="border rounded d-inline scroll-to-top" href="#page-top"
        ><i class="fas fa-angle-up"></i
      ></a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
    <script src="{% static 'talukas/js/bs-init.js' %}"></script>
    <script src="{% static 'talukas/js/theme.js' %}"></script>
  </body>
</html>

SIH-POSHAN/talukas/templates/talukas/index.html
{% extends 'talukas/base.html' %} {% block content %}

<div class="container-fluid">
  <div class="d-sm-flex justify-content-between align-items-center mb-4">
    <h3 class="text-dark mb-0">Dashboard</h3>
    <a
      class="btn btn-primary btn-sm d-none d-sm-inline-block"
      role="button"
      href="#"
      ><i class="fas fa-download fa-sm text-white-50"></i>&nbsp;Generate
      Report</a
    >
  </div>
  <div class="row">
    <div class="col-md-6 col-xl-3 mb-4">
      <div class="card shadow border-start-primary py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col me-2">
              <div class="text-uppercase text-primary fw-bold text-xs mb-1">
                <span>total schools&nbsp;</span>
              </div>
              <div class="text-dark fw-bold h5 mb-0"><span>715</span></div>
            </div>
            <div class="col-auto">
              <i class="far fa-building fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-3 mb-4">
      <div class="card shadow border-start-info py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col me-2">
              <div class="text-uppercase text-info fw-bold text-xs mb-1">
                <span>Schools with nutritional requisite achieved</span>
              </div>
              <div class="row g-0 align-items-center">
                <div class="col-auto">
                  <div class="text-dark fw-bold h5 mb-0 me-3">
                    <span>68%</span>
                  </div>
                </div>
                <div class="col">
                  <div class="progress progress-sm">
                    <div
                      class="progress-bar bg-success"
                      aria-valuenow="68"
                      aria-valuemin="0"
                      aria-valuemax="100"
                      style="width: 68%"
                    >
                      <span class="visually-hidden">68%</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-3 mb-4">
      <div class="card shadow border-start-success py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col me-2">
              <div class="text-uppercase text-success fw-bold text-xs mb-1">
                <span>Weekly meals searved</span>
              </div>
              <div class="text-dark fw-bold h5 mb-0"><span>35.4 K</span></div>
            </div>
            <div class="col-auto">
              <i class="fas fa-fire fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-xl-3 mb-4">
      <div class="card shadow border-start-warning py-2">
        <div class="card-body">
          <div class="row align-items-center no-gutters">
            <div class="col me-2">
              <div class="text-uppercase text-warning fw-bold text-xs mb-1">
                <span>daily scools reported</span>
              </div>
              <div class="text-dark fw-bold h5 mb-0"><span>491</span></div>
            </div>
            <div class="col-auto">
              <i class="fas fa-building fa-2x text-gray-300"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Start: Chart -->
  <div class="row">
    <div class="col-lg-7 col-xl-8">
      <div class="card shadow mb-4">
        <div
          class="card-header d-flex justify-content-between align-items-center"
        >
          <h6 class="text-primary fw-bold m-0">Students Retained</h6>
          <div class="dropdown no-arrow">
            <button
              class="btn btn-link btn-sm dropdown-toggle"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              type="button"
            >
              <i class="fas fa-ellipsis-v text-gray-400"></i>
            </button>
            <div
              class="dropdown-menu shadow dropdown-menu-end animated--fade-in"
            >
              <p class="text-center dropdown-header">GrAPH</p>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="chart-area">
            <canvas
              data-bss-chart='{"type":"line","data":{"labels":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"],"datasets":[{"label":"Retained","fill":true,"data":["31","41","40","49","51","49","56","68","100"],"backgroundColor":"rgba(78, 115, 223, 0.05)","borderColor":"rgba(78, 115, 223, 1)"}]},"options":{"maintainAspectRatio":false,"legend":{"display":false,"labels":{"fontStyle":"normal"}},"title":{"fontStyle":"normal"},"scales":{"xAxes":[{"gridLines":{"color":"rgb(234, 236, 244)","zeroLineColor":"rgb(234, 236, 244)","drawBorder":false,"drawTicks":false,"borderDash":["2"],"zeroLineBorderDash":["2"],"drawOnChartArea":false},"ticks":{"fontColor":"#858796","fontStyle":"normal","beginAtZero":true,"padding":20}}],"yAxes":[{"gridLines":{"color":"rgb(234, 236, 244)","zeroLineColor":"rgb(234, 236, 244)","drawBorder":false,"drawTicks":false,"borderDash":["2"],"zeroLineBorderDash":["2"]},"ticks":{"fontColor":"#858796","fontStyle":"normal","beginAtZero":true,"padding":20}}]}}}'
            ></canvas>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-5 col-xl-4">
      <div class="card shadow mb-4">
        <div
          class="card-header d-flex justify-content-between align-items-center"
        >
          <h6 class="text-primary fw-bold m-0">BMI</h6>
          <div class="dropdown no-arrow">
            <button
              class="btn btn-link btn-sm dropdown-toggle"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              type="button"
            >
              <i class="fas fa-ellipsis-v text-gray-400"></i>
            </button>
            <div
              class="dropdown-menu shadow dropdown-menu-end animated--fade-in"
            >
              <p class="text-center dropdown-header">BMI</p>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="chart-area" style="--bs-success-rgb: 200, 59, 28">
            <canvas
              data-bss-chart='{"type":"doughnut","data":{"labels":["Overweight","Healthy","Underweight"],"datasets":[{"label":"","backgroundColor":["#4e73df","#1cc88a","#36b9cc"],"borderColor":["#ffffff","#ffffff","#ffffff"],"data":["50","30","15"]}]},"options":{"maintainAspectRatio":false,"legend":{"display":false,"labels":{"fontStyle":"normal"},"reverse":false},"title":{"fontStyle":"normal","display":false}}}'
            ></canvas>
          </div>
          <div class="text-center small mt-4">
            <span class="me-2"
              ><i class="fas fa-circle text-primary"></i>Overweight</span
            ><span class="me-2"
              ><i class="fas fa-circle text-success"></i>Healthy</span
            ><span class="me-2"
              ><i class="fas fa-circle text-info"></i>Underweight</span
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End: Chart -->
  <div class="row">
    <div class="col-lg-6 mb-4">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="text-primary fw-bold m-0">
            Top 5 Schools (based on student retention)
          </h6>
        </div>
        <div class="card-body">
          <h4 class="small fw-bold">
            Thane Municipal Corporation School (61), Thane<span
              class="float-end"
              >82%</span
            >
          </h4>
          <div class="progress mb-4">
            <div
              class="progress-bar bg-success"
              aria-valuenow="82"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 82%"
            >
              <span class="visually-hidden">82%</span>
            </div>
          </div>
          <h4 class="small fw-bold">
            St. Xavier's High School, Airoli<span class="float-end">74%</span>
          </h4>
          <div class="progress mb-4">
            <div
              class="progress-bar bg-info"
              aria-valuenow="74"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 74%"
            >
              <span class="visually-hidden">74%</span>
            </div>
          </div>
          <h4 class="small fw-bold">
            Zilla Parishad Primary School, Dighe<span class="float-end"
              >71%</span
            >
          </h4>
          <div class="progress mb-4">
            <div
              class="progress-bar bg-primary"
              aria-valuenow="71"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 71%"
            >
              <span class="visually-hidden">71%</span>
            </div>
          </div>
          <h4 class="small fw-bold">
            Lok Puram Public School, Thane<span class="float-end">68%</span>
          </h4>
          <div class="progress mb-4">
            <div
              class="progress-bar bg-warning"
              aria-valuenow="68"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 68%"
            >
              <span class="visually-hidden">68%</span>
            </div>
          </div>
          <h4 class="small fw-bold">
            D.A.V. Public School, Thane<span class="float-end">64%</span>
          </h4>
          <div class="progress mb-4">
            <div
              class="progress-bar bg-danger"
              aria-valuenow="64"
              aria-valuemin="0"
              aria-valuemax="100"
              style="width: 64%"
            >
              <span class="visually-hidden">64%</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

SIH-POSHAN/talukas/templates/talukas/register-school.html
{% extends 'talukas/base.html' %} 

{% block content %}


<div class="container">
    <div class="card shadow-lg o-hidden border-0 my-5">
        <div class="card-body p-0">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h4 class="text-dark mb-4">Register a new School!</h4>
                        </div>
                        <form class="user">
                            <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleFirstName" placeholder="School Name" name="first_name"></div>
                            <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleFirstName-1" placeholder="Username" name="first_name"></div>
                            <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleFirstName-7" placeholder="Address Line 1" name="first_name"></div>
                            <div class="mb-3"><input class="form-control form-control-user" type="text" id="exampleFirstName-6" placeholder="Address Line 2" name="first_name"></div>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="exampleFirstName-4" placeholder="District" name="first_name"></div>
                                <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="exampleFirstName-5" placeholder="Pincode" name="last_name"></div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="text" id="exampleFirstName-2" placeholder="State" name="first_name"></div>
                                <div class="col-sm-6"><input class="form-control form-control-user" type="text" id="exampleFirstName-3" placeholder="India" name="last_name" disabled=""></div>
                            </div>
                            <div class="mb-3"><input class="form-control form-control-user" type="email" id="exampleInputEmail-1" aria-describedby="emailHelp" placeholder="Email Address" name="email"></div>
                            <div class="row mb-3">
                                <div class="col-sm-6 mb-3 mb-sm-0"><input class="form-control form-control-user" type="password" id="examplePasswordInput" placeholder="Password" name="password"></div>
                                <div class="col-sm-6"><input class="form-control form-control-user" type="password" id="exampleRepeatPasswordInput" placeholder="Repeat Password" name="password_repeat"></div>
                            </div><button class="btn btn-primary d-block btn-user w-100" type="submit">Register School</button>
                            <hr>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}