SIH-POSHAN/SIH_Meraki/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# import settings and static first
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('', views.indexview, name='home'),
    path('admin/login/', LoginView.as_view(template_name='accounts/login.html',
                                           redirect_authenticated_user=True),
         ),
    path('admin/', admin.site.urls),
    path('placeholder', views.PlaceholderView.as_view(),                name='placeholder'),
    path('accounts/', include('accounts.urls',                          namespace='accounts')),
    path('states/', include('states.urls',                              namespace='states')),
    path('districts/', include('districts.urls',                        namespace='districts')),
    path('schools/', include('schools.urls',                            namespace='schools')),
    path('talukas/', include('talukas.urls',                            namespace='talukas')),

]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

SIH-POSHAN/accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    PasswordChangeDoneView,
    PasswordChangeView
)
from .views import password_reset_request


app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='accounts/login.html',
                           redirect_authenticated_user=True),
         name='login'),

    path('logout/',
         LogoutView.as_view(),
         name='logout'),

    path('change_password/',
         PasswordChangeView.as_view(
             template_name='accounts/password_change_form.html',
             success_url=reverse_lazy('accounts:password_change_done')
         ),
         name='password_change'),

    path('password_change_done/',
         PasswordChangeDoneView.as_view(
             template_name='accounts/password_change_done.html'
         ),
         name='password_change_done'),

    # path('password_reset',
    #      PasswordResetView.as_view(
    #          template_name='accounts/password_reset.html',
    #          email_template_name='accounts/password_reset_email.html',
    #          subject_template_name='accounts/password_reset_subject.txt',
    #          success_url=reverse_lazy('accounts:password_reset_done')
    #      ),
    #      name='password_reset'),
    
    path('password_reset', password_reset_request, name='password_reset'),

    path('password_reset_done/',
         PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),

    path('password_reset_<uidb64>_<token>/',
         PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts:password_reset_complete')
         ),
         name='password_reset_confirm'),

    path('password_reset_complete/',
         PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),

]

SIH-POSHAN/schools/urls.py
from django.urls import path, include, reverse_lazy
from . import views


app_name = 'schools'

urlpatterns = [
    # SCHOOL
    path('dashboard/',                    views.dashboardView,                name='dashboard'),
    path('profile/',            views.profileView,                  name='profile'),
    path('update_profile_pic/', views.update_profile_pic,           name='update_profile_pic'),
    
    # MEAL
    path('meal/',views.Meal_add.as_view(),     name='todays_meal'),
    path('meal_detail/<pk>/',   views.MealDetailView.as_view(),     name='meal_detail'),
    
    # STUDENT
    path('register_students/',views.register_stu.as_view(),name='register'),
    path('create_students/',    views.StudentCreateView.as_view(),  name='create_students'),
    path('attendence/',         views.attendance.as_view(),               name='attendence'),
    path('student_details/<pk>/',  views.profile_get.as_view(), name='student_detail'),
    # path('regiter_students/')

    
    # CLASS
    path('create_class/',       views.ClassCreateView.as_view(),    name='create_class'),
    path('class_detail/<pk>/',  views.ClassDetailView.as_view(),    name='class_detail'),
    path('manage_class/',       views.ClassListView.as_view(),      name='manage_class'),
    path('update_class/<pk>/',  views.ClassUpdateView.as_view(),    name='update_class'),
    path('delete_class/<pk>/',  views.ClassDeleteView,              name='delete_class'),
    
]

SIH-POSHAN/states/urls.py
from django.urls import path, include, reverse_lazy
from .views import StateCreateView

app_name = 'states'

urlpatterns = [
    path('create_new/', StateCreateView.as_view(), name='create'), 
    
    ]


    

SIH-POSHAN/schools/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import RegexValidator
from talukas.models import Taluka
from districts.models import District
import os
import re
from django.contrib.auth.models import Group
from merakiiextras.common import get_current_datetime

def _(something):
    return something

def year_choices():
    choices = [(r,r) for r in reversed(range(1990, timezone.now().year+2))]
    # choices = choices.reverse()
    return choices

def current_year():
    return timezone.now().year+1

def std_choices():
    choices = [(-2, 'Jr. KG'),(-1, 'Sr. KG')]
    choices.extend([(r,r) for r in range(1,9)])
    return choices

def rename_upload_image_school_profile(instance, filename):
    ext = filename.split('.')[-1]
    filename = "profile/school/%s/%s/%s.%s.%s.%s" % (instance.user, instance.name, instance.udise_code, filename, get_current_datetime(), ext)
    return (os.path.join('images/', filename))

class School(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='schools')
    email = models.EmailField( max_length=254)
    name = models.CharField(max_length=150)
    udise_code = models.CharField(max_length=150, unique=True)
    profile_pic= models.ImageField(blank=False, upload_to=rename_upload_image_school_profile)
    # ADDRESS
    address_line1 = models.CharField( max_length=250)
    address_line2 = models.CharField( max_length=250)
    pincode = models.PositiveIntegerField()
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='schools')
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', 
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
                                )
    contact_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # Validators should be a list
    
    
    class Meta:
        verbose_name = "school"
        verbose_name_plural = "schools"

    def __str__(self):
        return f"{self.name} - ({self.district})"

    def get_absolute_url(self):
        return reverse("school_detail", kwargs={"pk": self.pk})
    
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        
        u = self.user
        u.email = self.email
        u.save()
        my_group = Group.objects.get(name='schools') 
        my_group.user_set.add(self.user)
        print(self.user)
        return super(School, self).save(*args, **kwargs)

class Class(models.Model):
    class_std = models.IntegerField(choices=std_choices())
    class_name = models.CharField(max_length=50, unique=True)
    year = models.IntegerField(choices=year_choices(), default=current_year)
    school = models.ForeignKey(School, on_delete=models.CASCADE,related_name='classes')

    class Meta:
        verbose_name = "class"
        verbose_name_plural = "clases"
        unique_together = ('class_name', 'year', 'school')

    def __str__(self):
        return f"{self.class_name} - ({self.school})"

    def get_absolute_url(self):
        return reverse("schools:class_detail", kwargs={"pk": self.pk})

class Student(models.Model):

    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    mother_name = models.CharField(max_length=150, blank=True, null=True)
    father_name = models.CharField(max_length=150, blank=True, null=True)
    dob = models.DateField()
    current_class = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='students')
    gr_no = models.CharField(max_length=50)
    roll_no = models.CharField(max_length=50)
    current_height = models.FloatField(blank=True, null=True)
    current_weight = models.FloatField(blank=True, null=True)
    # age = models.IntegerField(blank=True, null=True)
    created  = models.DateTimeField(editable=False, default=timezone.now)
    modified = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        verbose_name = "student"
        verbose_name_plural = "students"
        unique_together = ('current_class', 'gr_no',)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.gr_no}) ({self.current_class})"

    def get_absolute_url(self):
        return reverse("schools:student_detail", kwargs={"pk": self.pk})

    # def get_queryset(self, *args, **kwargs):
    #     qs = super(Student, self).get_queryset().annotate(age=int(self.calculate_age(self)))
    #     return qs
    
    @property    
    def age(self):
        born = self.dob
        today = timezone.now()
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))
        
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(Student, self).save(*args, **kwargs)
    
    @property    
    def calculate_age(self):
        born = self.dob
        today = timezone.now()
        return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

def rename_upload_image_meals(instance, filename):
    ext = filename.split('.')[-1]
    filename = "meals/%s/%s/%s.%s.%s.%s.%s" % (instance.school, instance.date, instance.name, str(instance.date), filename, get_current_datetime(), ext)
    return os.path.join('images/', filename)



class Meal(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='meals')
    name = models.CharField("Meal Name",max_length=999)
    date = models.DateField(default=timezone.now, blank=False, null=False)
    meal_pic= models.ImageField(blank=False, upload_to = rename_upload_image_meals)
    calories = models.FloatField(blank=True, null=True)
    proteins = models.FloatField(blank=True, null=True)

    class Meta:
        verbose_name = _("meal")
        verbose_name_plural = _("meals")
        unique_together = ('school','date')

    def __str__(self):
        return f"{self.name} ({self.date}) ({self.school.name})"

    def get_absolute_url(self):
        return reverse("schools:meal_detail", kwargs={"pk": self.pk})


class Attendence(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("attendence")
        verbose_name_plural = _("attendences")
        unique_together = ('meal', 'student')

    def __str__(self):
        return f"{self.student} ----> {self.meal.date}"

    def get_absolute_url(self):
        return reverse("attendence_detail", kwargs={"pk": self.pk})

SIH-POSHAN/schools/forms.py
from django import forms
from .models import Class, Student, Meal, Attendence, School

class ClassForm(forms.ModelForm):
    
    class Meta:
        model = Class
        # fields = '__all__'
        exclude = ['school']

class StudentForm(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))    
    
    class Meta:
        model = Student
        fields = ("__all__")
        # exclude = ('current_class')

class MealForm(forms.ModelForm):
    
    class Meta:
        model = Meal
        fields = ("__all__")

class SchoolForm(forms.ModelForm):
    
    class Meta:
        model = School
        fields = ("profile_pic",)
        widgets = {
            'profile_pic':forms.FileInput
        }

SIH-POSHAN/schools/templates/schools/attendence.html
{% extends 'schools/base.html' %}

{% block title %}404{% endblock title %}

{% block content %}

<div class="container-fluid">
    <h3 class="text-dark mb-4">Attendence</h3>
</div>

{% endblock content %}

SIH-POSHAN/schools/templates/schools/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Dashboard - Brand{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'schools/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
    <link rel="stylesheet" href="{% static 'schools/fonts/fontawesome-all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'schools/fonts/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'schools/fonts/fontawesome5-overrides.min.css' %}" />
    <link rel="stylesheet" href="{% static 'schools/css/Bootstrap-Image-Uploader.css' %}" />
    <link rel="stylesheet" href="{% static 'schools/css/Drag--Drop-Upload-Form.css' %}" />
    <script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>

</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0 toggled">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="#">
                    <div class="sidebar-brand-icon"><i class="fas fa-school"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>SCHOOL</span></div>
                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'schools:dashboard' %}"><i
                                class="fas fa-tachometer-alt"></i><span>Dashboard</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schools:profile' %}"><i
                                class="fas fa-user"></i><span>Profile</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schools:todays_meal' %}"><i
                                class="fa fa-apple"></i><span>Today's Meal</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schools:manage_class' %}"><i
                                class="fa fa-apple"></i><span>Manage Class</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-table"></i><span>Attendence</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="fas fa-table"></i><span>Student Details</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schools:create_students' %}"><i
                                class="fas fa-user-circle"></i><span>Register Students</span></a>
                    </li>
                </ul>
                <div class="text-center d-none d-md-inline">
                    <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button">
                            <i class="fas fa-bars"></i>
                        </button>
                        <ul class="navbar-nav flex-nowrap ms-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown"
                                    href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-end p-3 animated--grow-in"
                                    aria-labelledby="searchDropdown">
                                    <form class="me-auto navbar-search w-100">
                                        <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text"
                                                placeholder="Search for ..." />
                                            <div class="input-group-append">
                                                <button class="btn btn-primary py-0" type="button">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item dropdown no-arrow mx-1">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown"
                                        href="#"><span class="badge bg-danger badge-counter">1+</span><i
                                            class="fas fa-bell fa-fw"></i></a>
                                    <div class="dropdown-menu dropdown-menu-end dropdown-list animated--grow-in">
                                        <h6 class="dropdown-header">alerts center</h6>
                                        <a class="dropdown-item d-flex align-items-center" href="#">
                                            <div class="me-3">
                                                <div class="bg-primary icon-circle">
                                                    <i class="fas fa-file-alt text-white"></i>
                                                </div>
                                            </div>
                                            <div>
                                                <span class="small text-gray-500">December 12, 2019</span>
                                                <p>A new monthly report is ready to download!</p>
                                            </div>
                                        </a><a class="dropdown-item text-center small text-gray-500" href="#">Show All
                                            Alerts</a>
                                    </div>
                                </div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown"
                                        href="#"><span
                                            class="d-none d-lg-inline me-2 text-gray-600 small">{{user.username}}</span><img
                                            class="border rounded-circle img-profile"
                                            src="{{user.schools.profile_pic.url}}" /></a>
                                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
                                        <a class="dropdown-item" href="{% url 'schools:profile' %}"><i
                                                class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Profile</a><a
                                            class="dropdown-item" href="#"><i
                                                class="fas fa-list fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Activity
                                            log</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>

                <div>{% block content %}{% endblock content %}</div>
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright">
                        <span>Copyright © Meraki 2022</span>
                    </div>
                </div>
            </footer>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="{% static 'schools/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'schools/js/chart.min.js' %}"></script>
    <script src="{% static 'schools/js/bs-init.js' %}"></script>
    <script src="{% static 'schools/js/Bootstrap-Image-Uploader.js' %}"></script>
    <script src="{% static 'schools/js/theme.js' %}"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
      </script>
</body>

</html>

SIH-POSHAN/schools/templates/schools/blank.html
{% extends 'schools/base.html' %}

{% block title %}404{% endblock title %}

{% block content %}

<div class="container-fluid">
    <h3 class="text-dark mb-4">Blank Page</h3>
</div>

{% endblock content %}

SIH-POSHAN/schools/templates/schools/class_detail.html
{% extends "schools/base.html" %}

{% block content %}




<div class="container">

  <p>
    <a name="" id="" class="btn btn-primary" href="{% url 'schools:update_class' pk=class.id %}" role="button">
      UPdate Class
    </a>
  </p>
  <div class="card shadow-lg">
    <div class="card-body">
      <div class="table-responsive" style="text-align: center;">
        <table class="table">
          <thead>
            <tr style="text-align: center;">
              <th>First Name</th>
              <th>Last Name</th>
              <th>Gr no.</th>
              <th>DOB</th>
              <th>Gender</th>
              <th>BMI</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody>
            <!-- Start: Duplicate Table Row -->
            {% for student in student_list %}
            <tr>
              <td>{{student.first_name}}</td>
              <td>{{student.last_name}}</td>
              <td>{{student.gr_no}}</td>
              <td>{{student.dob}}</td>
              <td>{{student.gender}}</td>
              <td style="color: red;">6.1</td>
              <td style="text-align: center;">
                <a class="btn btn-info btn-icon-split" role="button" href="#">
                  <span class="text-white-50 icon">
                    <i class="far fa-edit"></i>
                  </span>
                  <span class="text-white text">Edit</span>
                </a>
              </td>
            </tr>
            {% endfor %}
            <!-- End: Duplicate Table Row -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



{% endblock content %}

SIH-POSHAN/schools/templates/schools/manage_class.html
{% extends 'schools/base.html' %}

<!-- Title -->
{% block title %} Meal Details {% endblock title%}
<!-- block content -->
{% block content %}
<script src="https://unpkg.com/htmx.org@1.8.0"
    integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc"
    crossorigin="anonymous"></script>

<div class="container">
    <p>
        <a name="" id="" class="btn btn-primary" href="{% url 'schools:create_class' %}" role="button">Add CLASS</a>

    </p>
    <div class="card-deck">

        {% for class in class_list %}
        <p>
        <div class="card shadow-lg">
            <div class="card-body">
                <h5 class="card-title">{{class.class_name}}</h5>
                <p class="card-text">
                    {{class.class_std}}
                    {{class.school}}
                    {{class.year}}
                <ul>
                    {% for student in class.students.all %}
                    <li>
                        {{student}}
                        <br>
                    </li>
                    {% endfor %}
                </ul>
                </p>
                <a href="{% url 'schools:class_detail' pk=class.id %}" class="btn btn-primary">Details</a>
                <a onclick="confirm_delete_class('{{class.id}}');" class="btn btn-danger" role="button">Delete</a>

            </div>


        </div>
        </p>

        {% endfor %}
    </div>


    {{class_list}}

    <!-- window.location.href = "/schools/delete_class/" + class_id_no; -->
    <script>
        function confirm_delete_class(class_id_no) {
            var r = confirm("Sure you want to delete the class?");
            if (r == true) {
                tempurl = "{% url 'schools:delete_class' '86212' %}"
                currrl = tempurl.replace('86212', class_id_no)
                window.location.href = currrl;
            }
        }
    </script>
</div>

{% endblock content %}

SIH-POSHAN/schools/templates/schools/todays-meal.html
{% extends 'schools/base.html' %} {% block title %}Meal Details{% endblock title%} {% block content %}
<div class="container-fluid">
    <div>
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            <!-- {{ form.as_p }} -->
            <!-- Start: Registration Form -->
            <div class="card shadow-lg o-hidden border-0 my-5">
                <div class="card-body p-0">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="p-5">
                                <div class="text-center">
                                    <h4 class="text-dark mb-4">Upload Mid-Day Meal Details</h4>
                                    <hr />
                                </div>
                                {{form.school}}
                                <form class="user">
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-4">
                                                <label class="col-form-label form-control-user" style="font-weight: bold">{{form.date.label}}</label>
                                            </div>
                                            <div class="col-8">
                                                {{form.date}}
                                                <script>
                                                    var xyz = document.querySelector("#id_date");
                                                    xyz.className += " form-control form-control-user";
                                                    xyz.type = "date";
                                                </script>
                                                <!-- <input class="form-control form-control-user" type="date" required=""> -->
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        {{form.name}}
                                        <script>
                                            var xyz = document.querySelector("#id_name");
                                            xyz.className += " form-control form-control-user";
                                            xyz.type = "text";
                                            xyz.placeholder = "Meal Name";
                                        </script>
                                        <!-- <input
                    class="form-control form-control-user"
                    type="text"
                    id="exampleFirstName-2"
                    placeholder="Meal Name"
                    name="first_name"
                    required=""
                  /> -->
                                    </div>
                                    <div class="mb-3">
                                        {{form.meal_pic}}
                                        <script>
                                            var xyz = document.querySelector("#id_meal_pic");
                                            xyz.className += " form-control";
                                            xyz.type = "file";
                                        </script>
                                        <!-- <input type="file" class="form-control" id="customFile" /> -->
                                    </div>
                                    <div class="row mb-3">
                                        <button class="btn btn-primary d-block btn-user w-100" type="submit"> Upload Image </button>
                                    </div>
                                    
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End: Registration Form -->
        </form>
    </div>
    <div></div>
</div> {% endblock content %}

SIH-POSHAN/schools/templates/schools/update_profile_pic.html
<form action="{% url 'schools:update_profile_pic' %}" method="post" enctype="multipart/form-data" id="upload_form">
    {% csrf_token %}
     
    {{form.as_p}}
     <input type="submit" value="Upload" class="btn btn-primary">

 </form>